/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.FacilityCarrierConnectionCutoffs;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * FacilityCarrierConnection
 */
@JsonPropertyOrder({
  FacilityCarrierConnection.JSON_PROPERTY_CUTOFFS
})
@JsonTypeName("FacilityCarrierConnection")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class FacilityCarrierConnection {
  public static final String JSON_PROPERTY_CUTOFFS = "cutoffs";
  private FacilityCarrierConnectionCutoffs cutoffs;


  public FacilityCarrierConnection cutoffs(FacilityCarrierConnectionCutoffs cutoffs) {
    
    this.cutoffs = cutoffs;
    return this;
  }

   /**
   * Get cutoffs
   * @return cutoffs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUTOFFS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FacilityCarrierConnectionCutoffs getCutoffs() {
    return cutoffs;
  }


  public void setCutoffs(FacilityCarrierConnectionCutoffs cutoffs) {
    this.cutoffs = cutoffs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacilityCarrierConnection facilityCarrierConnection = (FacilityCarrierConnection) o;
    return Objects.equals(this.cutoffs, facilityCarrierConnection.cutoffs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cutoffs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacilityCarrierConnection {\n");
    sb.append("    cutoffs: ").append(toIndentedString(cutoffs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

