/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * FacilityStockConfigurationAllOfShortpick
 */
@JsonPropertyOrder({
  FacilityStockConfigurationAllOfShortpick.JSON_PROPERTY_ACTIVE
})
@JsonTypeName("FacilityStockConfiguration_allOf_shortpick")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class FacilityStockConfigurationAllOfShortpick {
  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active = true;


  public FacilityStockConfigurationAllOfShortpick active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Inventory adjustment in the case of insufficient order picking
   * @return active
  **/
  @ApiModelProperty(required = true, value = "Inventory adjustment in the case of insufficient order picking")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacilityStockConfigurationAllOfShortpick facilityStockConfigurationAllOfShortpick = (FacilityStockConfigurationAllOfShortpick) o;
    return Objects.equals(this.active, facilityStockConfigurationAllOfShortpick.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacilityStockConfigurationAllOfShortpick {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

