/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.FacilityStockConfigurationAllOf;
import com.example.connectorpoc.ft.model.FacilityStockConfigurationAllOfListingReactivationAfter;
import com.example.connectorpoc.ft.model.FacilityStockConfigurationAllOfRetainedOfflineStock;
import com.example.connectorpoc.ft.model.FacilityStockConfigurationAllOfShortpick;
import com.example.connectorpoc.ft.model.VersionedResource;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * FacilityStockConfiguration
 */
@JsonPropertyOrder({
  FacilityStockConfiguration.JSON_PROPERTY_VERSION,
  FacilityStockConfiguration.JSON_PROPERTY_CREATED,
  FacilityStockConfiguration.JSON_PROPERTY_LAST_MODIFIED,
  FacilityStockConfiguration.JSON_PROPERTY_RETAINED_OFFLINE_STOCK,
  FacilityStockConfiguration.JSON_PROPERTY_LISTING_REACTIVATION_AFTER,
  FacilityStockConfiguration.JSON_PROPERTY_SHORTPICK
})
@JsonTypeName("FacilityStockConfiguration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class FacilityStockConfiguration {
  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_RETAINED_OFFLINE_STOCK = "retainedOfflineStock";
  private FacilityStockConfigurationAllOfRetainedOfflineStock retainedOfflineStock;

  public static final String JSON_PROPERTY_LISTING_REACTIVATION_AFTER = "listingReactivationAfter";
  private FacilityStockConfigurationAllOfListingReactivationAfter listingReactivationAfter;

  public static final String JSON_PROPERTY_SHORTPICK = "shortpick";
  private FacilityStockConfigurationAllOfShortpick shortpick;


  public FacilityStockConfiguration version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public FacilityStockConfiguration created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public FacilityStockConfiguration lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public FacilityStockConfiguration retainedOfflineStock(FacilityStockConfigurationAllOfRetainedOfflineStock retainedOfflineStock) {
    
    this.retainedOfflineStock = retainedOfflineStock;
    return this;
  }

   /**
   * Get retainedOfflineStock
   * @return retainedOfflineStock
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RETAINED_OFFLINE_STOCK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FacilityStockConfigurationAllOfRetainedOfflineStock getRetainedOfflineStock() {
    return retainedOfflineStock;
  }


  public void setRetainedOfflineStock(FacilityStockConfigurationAllOfRetainedOfflineStock retainedOfflineStock) {
    this.retainedOfflineStock = retainedOfflineStock;
  }


  public FacilityStockConfiguration listingReactivationAfter(FacilityStockConfigurationAllOfListingReactivationAfter listingReactivationAfter) {
    
    this.listingReactivationAfter = listingReactivationAfter;
    return this;
  }

   /**
   * Get listingReactivationAfter
   * @return listingReactivationAfter
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LISTING_REACTIVATION_AFTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FacilityStockConfigurationAllOfListingReactivationAfter getListingReactivationAfter() {
    return listingReactivationAfter;
  }


  public void setListingReactivationAfter(FacilityStockConfigurationAllOfListingReactivationAfter listingReactivationAfter) {
    this.listingReactivationAfter = listingReactivationAfter;
  }


  public FacilityStockConfiguration shortpick(FacilityStockConfigurationAllOfShortpick shortpick) {
    
    this.shortpick = shortpick;
    return this;
  }

   /**
   * Get shortpick
   * @return shortpick
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SHORTPICK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FacilityStockConfigurationAllOfShortpick getShortpick() {
    return shortpick;
  }


  public void setShortpick(FacilityStockConfigurationAllOfShortpick shortpick) {
    this.shortpick = shortpick;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacilityStockConfiguration facilityStockConfiguration = (FacilityStockConfiguration) o;
    return Objects.equals(this.version, facilityStockConfiguration.version) &&
        Objects.equals(this.created, facilityStockConfiguration.created) &&
        Objects.equals(this.lastModified, facilityStockConfiguration.lastModified) &&
        Objects.equals(this.retainedOfflineStock, facilityStockConfiguration.retainedOfflineStock) &&
        Objects.equals(this.listingReactivationAfter, facilityStockConfiguration.listingReactivationAfter) &&
        Objects.equals(this.shortpick, facilityStockConfiguration.shortpick);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, created, lastModified, retainedOfflineStock, listingReactivationAfter, shortpick);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacilityStockConfiguration {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    retainedOfflineStock: ").append(toIndentedString(retainedOfflineStock)).append("\n");
    sb.append("    listingReactivationAfter: ").append(toIndentedString(listingReactivationAfter)).append("\n");
    sb.append("    shortpick: ").append(toIndentedString(shortpick)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

