/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.CarrierReference;
import com.example.connectorpoc.ft.model.HandoverjobStatus;
import com.example.connectorpoc.ft.model.StrippedHandoverjob;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Handoverjob
 */
@JsonPropertyOrder({
  Handoverjob.JSON_PROPERTY_TARGET_TIME,
  Handoverjob.JSON_PROPERTY_ANONYMIZED,
  Handoverjob.JSON_PROPERTY_VERSION,
  Handoverjob.JSON_PROPERTY_CREATED,
  Handoverjob.JSON_PROPERTY_LAST_MODIFIED,
  Handoverjob.JSON_PROPERTY_ID,
  Handoverjob.JSON_PROPERTY_STATUS,
  Handoverjob.JSON_PROPERTY_TENANT_ORDER_ID,
  Handoverjob.JSON_PROPERTY_FACILITY_REF,
  Handoverjob.JSON_PROPERTY_PICK_JOB_REF,
  Handoverjob.JSON_PROPERTY_PARCEL_REF,
  Handoverjob.JSON_PROPERTY_SHIPMENT_REF,
  Handoverjob.JSON_PROPERTY_ORDER_DATE,
  Handoverjob.JSON_PROPERTY_CARRIER,
  Handoverjob.JSON_PROPERTY_CHANNEL
})
@JsonTypeName("Handoverjob")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class Handoverjob {
  public static final String JSON_PROPERTY_TARGET_TIME = "targetTime";
  private OffsetDateTime targetTime;

  public static final String JSON_PROPERTY_ANONYMIZED = "anonymized";
  private Boolean anonymized;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_STATUS = "status";
  private HandoverjobStatus status;

  public static final String JSON_PROPERTY_TENANT_ORDER_ID = "tenantOrderId";
  private String tenantOrderId;

  public static final String JSON_PROPERTY_FACILITY_REF = "facilityRef";
  private String facilityRef;

  public static final String JSON_PROPERTY_PICK_JOB_REF = "pickJobRef";
  private String pickJobRef;

  public static final String JSON_PROPERTY_PARCEL_REF = "parcelRef";
  private String parcelRef;

  public static final String JSON_PROPERTY_SHIPMENT_REF = "shipmentRef";
  private String shipmentRef;

  public static final String JSON_PROPERTY_ORDER_DATE = "orderDate";
  private OffsetDateTime orderDate;

  public static final String JSON_PROPERTY_CARRIER = "carrier";
  private CarrierReference carrier;

  /**
   * Gets or Sets channel
   */
  public enum ChannelEnum {
    DELIVERY("DELIVERY"),
    
    COLLECT("COLLECT");

    private String value;

    ChannelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChannelEnum fromValue(String value) {
      for (ChannelEnum b : ChannelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CHANNEL = "channel";
  private ChannelEnum channel;


  public Handoverjob targetTime(OffsetDateTime targetTime) {
    
    this.targetTime = targetTime;
    return this;
  }

   /**
   * At which time the result is expected.
   * @return targetTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "At which time the result is expected.")
  @JsonProperty(JSON_PROPERTY_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTargetTime() {
    return targetTime;
  }


  public void setTargetTime(OffsetDateTime targetTime) {
    this.targetTime = targetTime;
  }


  public Handoverjob anonymized(Boolean anonymized) {
    
    this.anonymized = anonymized;
    return this;
  }

   /**
   * Indicates if gdpr related data was anonymized
   * @return anonymized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if gdpr related data was anonymized")
  @JsonProperty(JSON_PROPERTY_ANONYMIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnonymized() {
    return anonymized;
  }


  public void setAnonymized(Boolean anonymized) {
    this.anonymized = anonymized;
  }


  public Handoverjob version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public Handoverjob created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public Handoverjob lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public Handoverjob id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of this handoverjob. It is generated during creation automatically and suits as the primary identifier of the described entity.
   * @return id
  **/
  @ApiModelProperty(example = "95EWrieX09OmeriXIUbb", required = true, value = "The id of this handoverjob. It is generated during creation automatically and suits as the primary identifier of the described entity.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Handoverjob status(HandoverjobStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public HandoverjobStatus getStatus() {
    return status;
  }


  public void setStatus(HandoverjobStatus status) {
    this.status = status;
  }


  public Handoverjob tenantOrderId(String tenantOrderId) {
    
    this.tenantOrderId = tenantOrderId;
    return this;
  }

   /**
   * Field can be used as a reference number in foreign systems, for example as a reference to the source system&#39;s identifier for this order.
   * @return tenantOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "R456728546", value = "Field can be used as a reference number in foreign systems, for example as a reference to the source system's identifier for this order.")
  @JsonProperty(JSON_PROPERTY_TENANT_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantOrderId() {
    return tenantOrderId;
  }


  public void setTenantOrderId(String tenantOrderId) {
    this.tenantOrderId = tenantOrderId;
  }


  public Handoverjob facilityRef(String facilityRef) {
    
    this.facilityRef = facilityRef;
    return this;
  }

   /**
   * The id of the facility reference.
   * @return facilityRef
  **/
  @ApiModelProperty(example = "Esb20gpHBL94X5NdMp3C", required = true, value = "The id of the facility reference.")
  @JsonProperty(JSON_PROPERTY_FACILITY_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFacilityRef() {
    return facilityRef;
  }


  public void setFacilityRef(String facilityRef) {
    this.facilityRef = facilityRef;
  }


  public Handoverjob pickJobRef(String pickJobRef) {
    
    this.pickJobRef = pickJobRef;
    return this;
  }

   /**
   * The reference to the pickjob for which the handoverjob is assigned to
   * @return pickJobRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ca525716-7208-4a63-a2a6-11274eb37f67-0", value = "The reference to the pickjob for which the handoverjob is assigned to")
  @JsonProperty(JSON_PROPERTY_PICK_JOB_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPickJobRef() {
    return pickJobRef;
  }


  public void setPickJobRef(String pickJobRef) {
    this.pickJobRef = pickJobRef;
  }


  public Handoverjob parcelRef(String parcelRef) {
    
    this.parcelRef = parcelRef;
    return this;
  }

   /**
   * The reference to the parcel.
   * @return parcelRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2fOge2ZGW54K4TgvDTQw", value = "The reference to the parcel.")
  @JsonProperty(JSON_PROPERTY_PARCEL_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParcelRef() {
    return parcelRef;
  }


  public void setParcelRef(String parcelRef) {
    this.parcelRef = parcelRef;
  }


  public Handoverjob shipmentRef(String shipmentRef) {
    
    this.shipmentRef = shipmentRef;
    return this;
  }

   /**
   * The reference to the shipment belonging to the handoverjob
   * @return shipmentRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Esb20gpHBL94X5NdMp3C", value = "The reference to the shipment belonging to the handoverjob")
  @JsonProperty(JSON_PROPERTY_SHIPMENT_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShipmentRef() {
    return shipmentRef;
  }


  public void setShipmentRef(String shipmentRef) {
    this.shipmentRef = shipmentRef;
  }


  public Handoverjob orderDate(OffsetDateTime orderDate) {
    
    this.orderDate = orderDate;
    return this;
  }

   /**
   * The date this order was created at the supplying system.
   * @return orderDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:50.525Z", value = "The date this order was created at the supplying system.")
  @JsonProperty(JSON_PROPERTY_ORDER_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getOrderDate() {
    return orderDate;
  }


  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }


  public Handoverjob carrier(CarrierReference carrier) {
    
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CARRIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CarrierReference getCarrier() {
    return carrier;
  }


  public void setCarrier(CarrierReference carrier) {
    this.carrier = carrier;
  }


  public Handoverjob channel(ChannelEnum channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChannelEnum getChannel() {
    return channel;
  }


  public void setChannel(ChannelEnum channel) {
    this.channel = channel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Handoverjob handoverjob = (Handoverjob) o;
    return Objects.equals(this.targetTime, handoverjob.targetTime) &&
        Objects.equals(this.anonymized, handoverjob.anonymized) &&
        Objects.equals(this.version, handoverjob.version) &&
        Objects.equals(this.created, handoverjob.created) &&
        Objects.equals(this.lastModified, handoverjob.lastModified) &&
        Objects.equals(this.id, handoverjob.id) &&
        Objects.equals(this.status, handoverjob.status) &&
        Objects.equals(this.tenantOrderId, handoverjob.tenantOrderId) &&
        Objects.equals(this.facilityRef, handoverjob.facilityRef) &&
        Objects.equals(this.pickJobRef, handoverjob.pickJobRef) &&
        Objects.equals(this.parcelRef, handoverjob.parcelRef) &&
        Objects.equals(this.shipmentRef, handoverjob.shipmentRef) &&
        Objects.equals(this.orderDate, handoverjob.orderDate) &&
        Objects.equals(this.carrier, handoverjob.carrier) &&
        Objects.equals(this.channel, handoverjob.channel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetTime, anonymized, version, created, lastModified, id, status, tenantOrderId, facilityRef, pickJobRef, parcelRef, shipmentRef, orderDate, carrier, channel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Handoverjob {\n");
    sb.append("    targetTime: ").append(toIndentedString(targetTime)).append("\n");
    sb.append("    anonymized: ").append(toIndentedString(anonymized)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenantOrderId: ").append(toIndentedString(tenantOrderId)).append("\n");
    sb.append("    facilityRef: ").append(toIndentedString(facilityRef)).append("\n");
    sb.append("    pickJobRef: ").append(toIndentedString(pickJobRef)).append("\n");
    sb.append("    parcelRef: ").append(toIndentedString(parcelRef)).append("\n");
    sb.append("    shipmentRef: ").append(toIndentedString(shipmentRef)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

