/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ArticleAttributeItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ListingAttributeItem
 */
@JsonPropertyOrder({
  ListingAttributeItem.JSON_PROPERTY_CATEGORY,
  ListingAttributeItem.JSON_PROPERTY_PRIORITY,
  ListingAttributeItem.JSON_PROPERTY_KEY,
  ListingAttributeItem.JSON_PROPERTY_VALUE
})
@JsonTypeName("ListingAttributeItem")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ListingAttributeItem {
  /**
   * This category is used by OCFF to customize implemented processes. Categorized attributes are used by various processes and tools throughout our platform. For a complete list of possible categories and the correct use of those please refer to the documentation. Default value: miscellaneous
   */
  public enum CategoryEnum {
    DESCRIPTIVE("descriptive"),
    
    MISCELLANEOUS("miscellaneous");

    private String value;

    CategoryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CategoryEnum fromValue(String value) {
      for (CategoryEnum b : CategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private CategoryEnum category;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private Long priority;

  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;


  public ListingAttributeItem category(CategoryEnum category) {
    
    this.category = category;
    return this;
  }

   /**
   * This category is used by OCFF to customize implemented processes. Categorized attributes are used by various processes and tools throughout our platform. For a complete list of possible categories and the correct use of those please refer to the documentation. Default value: miscellaneous
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "descriptive", value = "This category is used by OCFF to customize implemented processes. Categorized attributes are used by various processes and tools throughout our platform. For a complete list of possible categories and the correct use of those please refer to the documentation. Default value: miscellaneous")
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CategoryEnum getCategory() {
    return category;
  }


  public void setCategory(CategoryEnum category) {
    this.category = category;
  }


  public ListingAttributeItem priority(Long priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * This value gives the priority in the respective attribute category. The lower the value the higher is the priority, e.g. priority 1 is higher than priority 10. Attributes that have the highest priority might be selected for display in different articles of OCFF. Default Value is 1001. For details please contact the product owners.
   * minimum: 1
   * maximum: 1000
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "100", value = "This value gives the priority in the respective attribute category. The lower the value the higher is the priority, e.g. priority 1 is higher than priority 10. Attributes that have the highest priority might be selected for display in different articles of OCFF. Default Value is 1001. For details please contact the product owners.")
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPriority() {
    return priority;
  }


  public void setPriority(Long priority) {
    this.priority = priority;
  }


  public ListingAttributeItem key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Providing the key %%subtitle%% (see example) here will cause the value to appear for example in the App directly under the title. With all other attributes also the key will be displayed in the clients.
   * @return key
  **/
  @ApiModelProperty(example = "%%subtitle%%", required = true, value = "Providing the key %%subtitle%% (see example) here will cause the value to appear for example in the App directly under the title. With all other attributes also the key will be displayed in the clients.")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public ListingAttributeItem value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "585er Gold", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingAttributeItem listingAttributeItem = (ListingAttributeItem) o;
    return Objects.equals(this.category, listingAttributeItem.category) &&
        Objects.equals(this.priority, listingAttributeItem.priority) &&
        Objects.equals(this.key, listingAttributeItem.key) &&
        Objects.equals(this.value, listingAttributeItem.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, priority, key, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingAttributeItem {\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

