/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ListingAllOf;
import com.example.connectorpoc.ft.model.ListingAttributeItem;
import com.example.connectorpoc.ft.model.ListingForCreation;
import com.example.connectorpoc.ft.model.StockInformation;
import com.example.connectorpoc.ft.model.VersionedResource;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Listing
 */
@JsonPropertyOrder({
  Listing.JSON_PROPERTY_TENANT_ARTICLE_ID,
  Listing.JSON_PROPERTY_PRICE,
  Listing.JSON_PROPERTY_STOCKINFORMATION,
  Listing.JSON_PROPERTY_TITLE,
  Listing.JSON_PROPERTY_IMAGE_URL,
  Listing.JSON_PROPERTY_ATTRIBUTES,
  Listing.JSON_PROPERTY_VERSION,
  Listing.JSON_PROPERTY_CREATED,
  Listing.JSON_PROPERTY_LAST_MODIFIED,
  Listing.JSON_PROPERTY_ID,
  Listing.JSON_PROPERTY_FACILITY_ID,
  Listing.JSON_PROPERTY_STATUS
})
@JsonTypeName("Listing")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class Listing {
  public static final String JSON_PROPERTY_TENANT_ARTICLE_ID = "tenantArticleId";
  private String tenantArticleId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private BigDecimal price;

  public static final String JSON_PROPERTY_STOCKINFORMATION = "stockinformation";
  private StockInformation stockinformation;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_IMAGE_URL = "imageUrl";
  private String imageUrl;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private List<ListingAttributeItem> attributes = null;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_FACILITY_ID = "facilityId";
  private String facilityId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    INACTIVE("INACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;


  public Listing tenantArticleId(String tenantArticleId) {
    
    this.tenantArticleId = tenantArticleId;
    return this;
  }

   /**
   * This is a reference to an article Id
   * @return tenantArticleId
  **/
  @ApiModelProperty(example = "4711", required = true, value = "This is a reference to an article Id")
  @JsonProperty(JSON_PROPERTY_TENANT_ARTICLE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTenantArticleId() {
    return tenantArticleId;
  }


  public void setTenantArticleId(String tenantArticleId) {
    this.tenantArticleId = tenantArticleId;
  }


  public Listing price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1200.0", value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public Listing stockinformation(StockInformation stockinformation) {
    
    this.stockinformation = stockinformation;
    return this;
  }

   /**
   * Get stockinformation
   * @return stockinformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOCKINFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StockInformation getStockinformation() {
    return stockinformation;
  }


  public void setStockinformation(StockInformation stockinformation) {
    this.stockinformation = stockinformation;
  }


  public Listing title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * a title describing the article
   * @return title
  **/
  @ApiModelProperty(example = "Adidas Superstar", required = true, value = "a title describing the article")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Listing imageUrl(String imageUrl) {
    
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * A web link to a picture of this article. Please make sure that no authentication is required to fetch the image!
   * @return imageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A web link to a picture of this article. Please make sure that no authentication is required to fetch the image!")
  @JsonProperty(JSON_PROPERTY_IMAGE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageUrl() {
    return imageUrl;
  }


  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }


  public Listing attributes(List<ListingAttributeItem> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public Listing addAttributesItem(ListingAttributeItem attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ListingAttributeItem> getAttributes() {
    return attributes;
  }


  public void setAttributes(List<ListingAttributeItem> attributes) {
    this.attributes = attributes;
  }


  public Listing version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public Listing created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public Listing lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public Listing id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "fsfdsf87fsd", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Listing facilityId(String facilityId) {
    
    this.facilityId = facilityId;
    return this;
  }

   /**
   * This is a reference to a facility
   * @return facilityId
  **/
  @ApiModelProperty(example = "4711", required = true, value = "This is a reference to a facility")
  @JsonProperty(JSON_PROPERTY_FACILITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFacilityId() {
    return facilityId;
  }


  public void setFacilityId(String facilityId) {
    this.facilityId = facilityId;
  }


  public Listing status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Listing listing = (Listing) o;
    return Objects.equals(this.tenantArticleId, listing.tenantArticleId) &&
        Objects.equals(this.price, listing.price) &&
        Objects.equals(this.stockinformation, listing.stockinformation) &&
        Objects.equals(this.title, listing.title) &&
        Objects.equals(this.imageUrl, listing.imageUrl) &&
        Objects.equals(this.attributes, listing.attributes) &&
        Objects.equals(this.version, listing.version) &&
        Objects.equals(this.created, listing.created) &&
        Objects.equals(this.lastModified, listing.lastModified) &&
        Objects.equals(this.id, listing.id) &&
        Objects.equals(this.facilityId, listing.facilityId) &&
        Objects.equals(this.status, listing.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantArticleId, price, stockinformation, title, imageUrl, attributes, version, created, lastModified, id, facilityId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Listing {\n");
    sb.append("    tenantArticleId: ").append(toIndentedString(tenantArticleId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    stockinformation: ").append(toIndentedString(stockinformation)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    facilityId: ").append(toIndentedString(facilityId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

