/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ModifyShortpickActionAllOf
 */
@JsonPropertyOrder({
  ModifyShortpickActionAllOf.JSON_PROPERTY_ACTION,
  ModifyShortpickActionAllOf.JSON_PROPERTY_ACTIVE
})
@JsonTypeName("ModifyShortpickAction_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ModifyShortpickActionAllOf {
  /**
   * Use value &#39;ModifyShortpick&#39;, if you want to modify the ModifyShortPick of a facility
   */
  public enum ActionEnum {
    MODIFYSHORTPICK("ModifyShortpick");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active = true;


  public ModifyShortpickActionAllOf action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * Use value &#39;ModifyShortpick&#39;, if you want to modify the ModifyShortPick of a facility
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Use value 'ModifyShortpick', if you want to modify the ModifyShortPick of a facility")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public ModifyShortpickActionAllOf active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Inventory adjustment in the case of insufficient order picking
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Inventory adjustment in the case of insufficient order picking")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyShortpickActionAllOf modifyShortpickActionAllOf = (ModifyShortpickActionAllOf) o;
    return Objects.equals(this.action, modifyShortpickActionAllOf.action) &&
        Objects.equals(this.active, modifyShortpickActionAllOf.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, active);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyShortpickActionAllOf {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

