/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.FacilityForCreationContact;
import com.example.connectorpoc.ft.model.FacilityForCreationServices;
import com.example.connectorpoc.ft.model.ModifyFacilityAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ModifyFacilityActionAllOf
 */
@JsonPropertyOrder({
  ModifyFacilityActionAllOf.JSON_PROPERTY_ACTION,
  ModifyFacilityActionAllOf.JSON_PROPERTY_NAME,
  ModifyFacilityActionAllOf.JSON_PROPERTY_TENANT_FACILITY_ID,
  ModifyFacilityActionAllOf.JSON_PROPERTY_LOCATION_TYPE,
  ModifyFacilityActionAllOf.JSON_PROPERTY_ADDRESS,
  ModifyFacilityActionAllOf.JSON_PROPERTY_CONTACT,
  ModifyFacilityActionAllOf.JSON_PROPERTY_STATUS,
  ModifyFacilityActionAllOf.JSON_PROPERTY_SERVICES,
  ModifyFacilityActionAllOf.JSON_PROPERTY_CUSTOM_ATTRIBUTES
})
@JsonTypeName("ModifyFacilityAction_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ModifyFacilityActionAllOf {
  /**
   * Use value &#39;ModifyFacility&#39;, because you want to modify a facility
   */
  public enum ActionEnum {
    MODIFYFACILITY("ModifyFacility");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TENANT_FACILITY_ID = "tenantFacilityId";
  private String tenantFacilityId;

  /**
   * Gets or Sets locationType
   */
  public enum LocationTypeEnum {
    STORE("STORE"),
    
    WAREHOUSE("WAREHOUSE");

    private String value;

    LocationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LocationTypeEnum fromValue(String value) {
      for (LocationTypeEnum b : LocationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LOCATION_TYPE = "locationType";
  private LocationTypeEnum locationType = LocationTypeEnum.STORE;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private ModifyFacilityAddress address = null;

  public static final String JSON_PROPERTY_CONTACT = "contact";
  private FacilityForCreationContact contact;

  /**
   * The state of the facility. ONLINE means that this facility can process new orders and pickjobs, SUSPENDED means it cannot get new orders but is able to fulfill the current workload and OFFLINE means that it cannot fulfill any new or existing orders. Processes already running might be rescheduled to another facility depending on the preferences.
   */
  public enum StatusEnum {
    ONLINE("ONLINE"),
    
    SUSPENDED("SUSPENDED"),
    
    OFFLINE("OFFLINE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_SERVICES = "services";
  private List<FacilityForCreationServices> services = null;

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTES = "customAttributes";
  private Object customAttributes;


  public ModifyFacilityActionAllOf action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * Use value &#39;ModifyFacility&#39;, because you want to modify a facility
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Use value 'ModifyFacility', because you want to modify a facility")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public ModifyFacilityActionAllOf name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Hamburg NW2", value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ModifyFacilityActionAllOf tenantFacilityId(String tenantFacilityId) {
    
    this.tenantFacilityId = tenantFacilityId;
    return this;
  }

   /**
   * The id of the facility in the tenants own system
   * @return tenantFacilityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "K12345", value = "The id of the facility in the tenants own system")
  @JsonProperty(JSON_PROPERTY_TENANT_FACILITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantFacilityId() {
    return tenantFacilityId;
  }


  public void setTenantFacilityId(String tenantFacilityId) {
    this.tenantFacilityId = tenantFacilityId;
  }


  public ModifyFacilityActionAllOf locationType(LocationTypeEnum locationType) {
    
    this.locationType = locationType;
    return this;
  }

   /**
   * Get locationType
   * @return locationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocationTypeEnum getLocationType() {
    return locationType;
  }


  public void setLocationType(LocationTypeEnum locationType) {
    this.locationType = locationType;
  }


  public ModifyFacilityActionAllOf address(ModifyFacilityAddress address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModifyFacilityAddress getAddress() {
    return address;
  }


  public void setAddress(ModifyFacilityAddress address) {
    this.address = address;
  }


  public ModifyFacilityActionAllOf contact(FacilityForCreationContact contact) {
    
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FacilityForCreationContact getContact() {
    return contact;
  }


  public void setContact(FacilityForCreationContact contact) {
    this.contact = contact;
  }


  public ModifyFacilityActionAllOf status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * The state of the facility. ONLINE means that this facility can process new orders and pickjobs, SUSPENDED means it cannot get new orders but is able to fulfill the current workload and OFFLINE means that it cannot fulfill any new or existing orders. Processes already running might be rescheduled to another facility depending on the preferences.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The state of the facility. ONLINE means that this facility can process new orders and pickjobs, SUSPENDED means it cannot get new orders but is able to fulfill the current workload and OFFLINE means that it cannot fulfill any new or existing orders. Processes already running might be rescheduled to another facility depending on the preferences.")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public ModifyFacilityActionAllOf services(List<FacilityForCreationServices> services) {
    
    this.services = services;
    return this;
  }

  public ModifyFacilityActionAllOf addServicesItem(FacilityForCreationServices servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FacilityForCreationServices> getServices() {
    return services;
  }


  public void setServices(List<FacilityForCreationServices> services) {
    this.services = services;
  }


  public ModifyFacilityActionAllOf customAttributes(Object customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

   /**
   * Attributes that can be added to the facility. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attributes that can be added to the facility. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(Object customAttributes) {
    this.customAttributes = customAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyFacilityActionAllOf modifyFacilityActionAllOf = (ModifyFacilityActionAllOf) o;
    return Objects.equals(this.action, modifyFacilityActionAllOf.action) &&
        Objects.equals(this.name, modifyFacilityActionAllOf.name) &&
        Objects.equals(this.tenantFacilityId, modifyFacilityActionAllOf.tenantFacilityId) &&
        Objects.equals(this.locationType, modifyFacilityActionAllOf.locationType) &&
        Objects.equals(this.address, modifyFacilityActionAllOf.address) &&
        Objects.equals(this.contact, modifyFacilityActionAllOf.contact) &&
        Objects.equals(this.status, modifyFacilityActionAllOf.status) &&
        Objects.equals(this.services, modifyFacilityActionAllOf.services) &&
        Objects.equals(this.customAttributes, modifyFacilityActionAllOf.customAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, name, tenantFacilityId, locationType, address, contact, status, services, customAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyFacilityActionAllOf {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tenantFacilityId: ").append(toIndentedString(tenantFacilityId)).append("\n");
    sb.append("    locationType: ").append(toIndentedString(locationType)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

