/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.FacilityStockConfigurationAllOfListingReactivationAfter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ModifyListingReactivationAfterActionAllOf
 */
@JsonPropertyOrder({
  ModifyListingReactivationAfterActionAllOf.JSON_PROPERTY_ACTION,
  ModifyListingReactivationAfterActionAllOf.JSON_PROPERTY_LISTING_REACTIVATION_AFTER
})
@JsonTypeName("ModifyListingReactivationAfterAction_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ModifyListingReactivationAfterActionAllOf {
  /**
   * Use value &#39;ModifyListingReactivationAfter&#39;, if you want to modify the listingReactivationAfter of a facility
   */
  public enum ActionEnum {
    MODIFYLISTINGREACTIVATIONAFTER("ModifyListingReactivationAfter");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public static final String JSON_PROPERTY_LISTING_REACTIVATION_AFTER = "listingReactivationAfter";
  private FacilityStockConfigurationAllOfListingReactivationAfter listingReactivationAfter;


  public ModifyListingReactivationAfterActionAllOf action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * Use value &#39;ModifyListingReactivationAfter&#39;, if you want to modify the listingReactivationAfter of a facility
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Use value 'ModifyListingReactivationAfter', if you want to modify the listingReactivationAfter of a facility")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public ModifyListingReactivationAfterActionAllOf listingReactivationAfter(FacilityStockConfigurationAllOfListingReactivationAfter listingReactivationAfter) {
    
    this.listingReactivationAfter = listingReactivationAfter;
    return this;
  }

   /**
   * Get listingReactivationAfter
   * @return listingReactivationAfter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LISTING_REACTIVATION_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FacilityStockConfigurationAllOfListingReactivationAfter getListingReactivationAfter() {
    return listingReactivationAfter;
  }


  public void setListingReactivationAfter(FacilityStockConfigurationAllOfListingReactivationAfter listingReactivationAfter) {
    this.listingReactivationAfter = listingReactivationAfter;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyListingReactivationAfterActionAllOf modifyListingReactivationAfterActionAllOf = (ModifyListingReactivationAfterActionAllOf) o;
    return Objects.equals(this.action, modifyListingReactivationAfterActionAllOf.action) &&
        Objects.equals(this.listingReactivationAfter, modifyListingReactivationAfterActionAllOf.listingReactivationAfter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, listingReactivationAfter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyListingReactivationAfterActionAllOf {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    listingReactivationAfter: ").append(toIndentedString(listingReactivationAfter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

