/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ModifyAddress;
import com.example.connectorpoc.ft.model.ModifyAddressPhoneNumbers;
import com.example.connectorpoc.ft.model.ModifyFacilityAddressAllOf;
import com.example.connectorpoc.ft.model.ModifyFacilityAddressAllOfEmailAddresses;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ModifyFacilityAddress
 */
@JsonPropertyOrder({
  ModifyFacilityAddress.JSON_PROPERTY_STREET,
  ModifyFacilityAddress.JSON_PROPERTY_HOUSE_NUMBER,
  ModifyFacilityAddress.JSON_PROPERTY_POSTAL_CODE,
  ModifyFacilityAddress.JSON_PROPERTY_CITY,
  ModifyFacilityAddress.JSON_PROPERTY_COUNTRY,
  ModifyFacilityAddress.JSON_PROPERTY_PHONE_NUMBERS,
  ModifyFacilityAddress.JSON_PROPERTY_ADDITIONAL_ADDRESS_INFO,
  ModifyFacilityAddress.JSON_PROPERTY_CUSTOM_ATTRIBUTES,
  ModifyFacilityAddress.JSON_PROPERTY_COMPANY_NAME,
  ModifyFacilityAddress.JSON_PROPERTY_EMAIL_ADDRESSES
})
@JsonTypeName("ModifyFacilityAddress")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ModifyFacilityAddress {
  public static final String JSON_PROPERTY_STREET = "street";
  private String street;

  public static final String JSON_PROPERTY_HOUSE_NUMBER = "houseNumber";
  private String houseNumber;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_PHONE_NUMBERS = "phoneNumbers";
  private List<ModifyAddressPhoneNumbers> phoneNumbers = null;

  public static final String JSON_PROPERTY_ADDITIONAL_ADDRESS_INFO = "additionalAddressInfo";
  private String additionalAddressInfo;

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTES = "customAttributes";
  private Object customAttributes;

  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  private String companyName;

  public static final String JSON_PROPERTY_EMAIL_ADDRESSES = "emailAddresses";
  private List<ModifyFacilityAddressAllOfEmailAddresses> emailAddresses = null;


  public ModifyFacilityAddress street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Hauptstr.", value = "")
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreet() {
    return street;
  }


  public void setStreet(String street) {
    this.street = street;
  }


  public ModifyFacilityAddress houseNumber(String houseNumber) {
    
    this.houseNumber = houseNumber;
    return this;
  }

   /**
   * Get houseNumber
   * @return houseNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "42a", value = "")
  @JsonProperty(JSON_PROPERTY_HOUSE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHouseNumber() {
    return houseNumber;
  }


  public void setHouseNumber(String houseNumber) {
    this.houseNumber = houseNumber;
  }


  public ModifyFacilityAddress postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "40764", value = "")
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public ModifyFacilityAddress city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Langenfeld", value = "")
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public ModifyFacilityAddress country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * A two-digit country code as per ISO 3166-1 alpha-2
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DE", value = "A two-digit country code as per ISO 3166-1 alpha-2")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public ModifyFacilityAddress phoneNumbers(List<ModifyAddressPhoneNumbers> phoneNumbers) {
    
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public ModifyFacilityAddress addPhoneNumbersItem(ModifyAddressPhoneNumbers phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * Get phoneNumbers
   * @return phoneNumbers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHONE_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModifyAddressPhoneNumbers> getPhoneNumbers() {
    return phoneNumbers;
  }


  public void setPhoneNumbers(List<ModifyAddressPhoneNumbers> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }


  public ModifyFacilityAddress additionalAddressInfo(String additionalAddressInfo) {
    
    this.additionalAddressInfo = additionalAddressInfo;
    return this;
  }

   /**
   * Get additionalAddressInfo
   * @return additionalAddressInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "to care of: Mrs. Müller", value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADDRESS_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalAddressInfo() {
    return additionalAddressInfo;
  }


  public void setAdditionalAddressInfo(String additionalAddressInfo) {
    this.additionalAddressInfo = additionalAddressInfo;
  }


  public ModifyFacilityAddress customAttributes(Object customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

   /**
   * Attributes that can be added to the address. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attributes that can be added to the address. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(Object customAttributes) {
    this.customAttributes = customAttributes;
  }


  public ModifyFacilityAddress companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Speedy Boxales Ltd.", value = "")
  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public ModifyFacilityAddress emailAddresses(List<ModifyFacilityAddressAllOfEmailAddresses> emailAddresses) {
    
    this.emailAddresses = emailAddresses;
    return this;
  }

  public ModifyFacilityAddress addEmailAddressesItem(ModifyFacilityAddressAllOfEmailAddresses emailAddressesItem) {
    if (this.emailAddresses == null) {
      this.emailAddresses = new ArrayList<>();
    }
    this.emailAddresses.add(emailAddressesItem);
    return this;
  }

   /**
   * Get emailAddresses
   * @return emailAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModifyFacilityAddressAllOfEmailAddresses> getEmailAddresses() {
    return emailAddresses;
  }


  public void setEmailAddresses(List<ModifyFacilityAddressAllOfEmailAddresses> emailAddresses) {
    this.emailAddresses = emailAddresses;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyFacilityAddress modifyFacilityAddress = (ModifyFacilityAddress) o;
    return Objects.equals(this.street, modifyFacilityAddress.street) &&
        Objects.equals(this.houseNumber, modifyFacilityAddress.houseNumber) &&
        Objects.equals(this.postalCode, modifyFacilityAddress.postalCode) &&
        Objects.equals(this.city, modifyFacilityAddress.city) &&
        Objects.equals(this.country, modifyFacilityAddress.country) &&
        Objects.equals(this.phoneNumbers, modifyFacilityAddress.phoneNumbers) &&
        Objects.equals(this.additionalAddressInfo, modifyFacilityAddress.additionalAddressInfo) &&
        Objects.equals(this.customAttributes, modifyFacilityAddress.customAttributes) &&
        Objects.equals(this.companyName, modifyFacilityAddress.companyName) &&
        Objects.equals(this.emailAddresses, modifyFacilityAddress.emailAddresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, houseNumber, postalCode, city, country, phoneNumbers, additionalAddressInfo, customAttributes, companyName, emailAddresses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyFacilityAddress {\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    additionalAddressInfo: ").append(toIndentedString(additionalAddressInfo)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    emailAddresses: ").append(toIndentedString(emailAddresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

