/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ModifyFacilityAddressAllOfEmailAddresses;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ModifyFacilityAddressAllOf
 */
@JsonPropertyOrder({
  ModifyFacilityAddressAllOf.JSON_PROPERTY_COMPANY_NAME,
  ModifyFacilityAddressAllOf.JSON_PROPERTY_EMAIL_ADDRESSES
})
@JsonTypeName("ModifyFacilityAddress_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ModifyFacilityAddressAllOf {
  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  private String companyName;

  public static final String JSON_PROPERTY_EMAIL_ADDRESSES = "emailAddresses";
  private List<ModifyFacilityAddressAllOfEmailAddresses> emailAddresses = null;


  public ModifyFacilityAddressAllOf companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Speedy Boxales Ltd.", value = "")
  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public ModifyFacilityAddressAllOf emailAddresses(List<ModifyFacilityAddressAllOfEmailAddresses> emailAddresses) {
    
    this.emailAddresses = emailAddresses;
    return this;
  }

  public ModifyFacilityAddressAllOf addEmailAddressesItem(ModifyFacilityAddressAllOfEmailAddresses emailAddressesItem) {
    if (this.emailAddresses == null) {
      this.emailAddresses = new ArrayList<>();
    }
    this.emailAddresses.add(emailAddressesItem);
    return this;
  }

   /**
   * Get emailAddresses
   * @return emailAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModifyFacilityAddressAllOfEmailAddresses> getEmailAddresses() {
    return emailAddresses;
  }


  public void setEmailAddresses(List<ModifyFacilityAddressAllOfEmailAddresses> emailAddresses) {
    this.emailAddresses = emailAddresses;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyFacilityAddressAllOf modifyFacilityAddressAllOf = (ModifyFacilityAddressAllOf) o;
    return Objects.equals(this.companyName, modifyFacilityAddressAllOf.companyName) &&
        Objects.equals(this.emailAddresses, modifyFacilityAddressAllOf.emailAddresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, emailAddresses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyFacilityAddressAllOf {\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    emailAddresses: ").append(toIndentedString(emailAddresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

