/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.DeliveryPreferences;
import com.example.connectorpoc.ft.model.OrderForCreationConsumer;
import com.example.connectorpoc.ft.model.OrderLineItemForCreation;
import com.example.connectorpoc.ft.model.OrderStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * OrderForCreation
 */
@JsonPropertyOrder({
  OrderForCreation.JSON_PROPERTY_ORDER_DATE,
  OrderForCreation.JSON_PROPERTY_CONSUMER,
  OrderForCreation.JSON_PROPERTY_TENANT_ORDER_ID,
  OrderForCreation.JSON_PROPERTY_STATUS,
  OrderForCreation.JSON_PROPERTY_ORDER_LINE_ITEMS,
  OrderForCreation.JSON_PROPERTY_DELIVERY_PREFERENCES,
  OrderForCreation.JSON_PROPERTY_CUSTOM_ATTRIBUTES
})
@JsonTypeName("OrderForCreation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class OrderForCreation {
  public static final String JSON_PROPERTY_ORDER_DATE = "orderDate";
  private OffsetDateTime orderDate;

  public static final String JSON_PROPERTY_CONSUMER = "consumer";
  private OrderForCreationConsumer consumer;

  public static final String JSON_PROPERTY_TENANT_ORDER_ID = "tenantOrderId";
  private String tenantOrderId;

  public static final String JSON_PROPERTY_STATUS = "status";
  private OrderStatus status;

  public static final String JSON_PROPERTY_ORDER_LINE_ITEMS = "orderLineItems";
  private List<OrderLineItemForCreation> orderLineItems = new ArrayList<>();

  public static final String JSON_PROPERTY_DELIVERY_PREFERENCES = "deliveryPreferences";
  private DeliveryPreferences deliveryPreferences;

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTES = "customAttributes";
  private Object customAttributes;


  public OrderForCreation orderDate(OffsetDateTime orderDate) {
    
    this.orderDate = orderDate;
    return this;
  }

   /**
   * The date this order was created at the supplying system.
   * @return orderDate
  **/
  @ApiModelProperty(example = "2020-02-03T08:45:50.525Z", required = true, value = "The date this order was created at the supplying system.")
  @JsonProperty(JSON_PROPERTY_ORDER_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getOrderDate() {
    return orderDate;
  }


  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }


  public OrderForCreation consumer(OrderForCreationConsumer consumer) {
    
    this.consumer = consumer;
    return this;
  }

   /**
   * Get consumer
   * @return consumer
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONSUMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OrderForCreationConsumer getConsumer() {
    return consumer;
  }


  public void setConsumer(OrderForCreationConsumer consumer) {
    this.consumer = consumer;
  }


  public OrderForCreation tenantOrderId(String tenantOrderId) {
    
    this.tenantOrderId = tenantOrderId;
    return this;
  }

   /**
   * Field can be used as a reference number in foreign systems, for example as a reference to the source system&#39;s identifier for this order.
   * @return tenantOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "R456728546", value = "Field can be used as a reference number in foreign systems, for example as a reference to the source system's identifier for this order.")
  @JsonProperty(JSON_PROPERTY_TENANT_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantOrderId() {
    return tenantOrderId;
  }


  public void setTenantOrderId(String tenantOrderId) {
    this.tenantOrderId = tenantOrderId;
  }


  public OrderForCreation status(OrderStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderStatus getStatus() {
    return status;
  }


  public void setStatus(OrderStatus status) {
    this.status = status;
  }


  public OrderForCreation orderLineItems(List<OrderLineItemForCreation> orderLineItems) {
    
    this.orderLineItems = orderLineItems;
    return this;
  }

  public OrderForCreation addOrderLineItemsItem(OrderLineItemForCreation orderLineItemsItem) {
    this.orderLineItems.add(orderLineItemsItem);
    return this;
  }

   /**
   * Get orderLineItems
   * @return orderLineItems
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_LINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<OrderLineItemForCreation> getOrderLineItems() {
    return orderLineItems;
  }


  public void setOrderLineItems(List<OrderLineItemForCreation> orderLineItems) {
    this.orderLineItems = orderLineItems;
  }


  public OrderForCreation deliveryPreferences(DeliveryPreferences deliveryPreferences) {
    
    this.deliveryPreferences = deliveryPreferences;
    return this;
  }

   /**
   * Get deliveryPreferences
   * @return deliveryPreferences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_PREFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryPreferences getDeliveryPreferences() {
    return deliveryPreferences;
  }


  public void setDeliveryPreferences(DeliveryPreferences deliveryPreferences) {
    this.deliveryPreferences = deliveryPreferences;
  }


  public OrderForCreation customAttributes(Object customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

   /**
   * Attributes that can be added to the order. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attributes that can be added to the order. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(Object customAttributes) {
    this.customAttributes = customAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderForCreation orderForCreation = (OrderForCreation) o;
    return Objects.equals(this.orderDate, orderForCreation.orderDate) &&
        Objects.equals(this.consumer, orderForCreation.consumer) &&
        Objects.equals(this.tenantOrderId, orderForCreation.tenantOrderId) &&
        Objects.equals(this.status, orderForCreation.status) &&
        Objects.equals(this.orderLineItems, orderForCreation.orderLineItems) &&
        Objects.equals(this.deliveryPreferences, orderForCreation.deliveryPreferences) &&
        Objects.equals(this.customAttributes, orderForCreation.customAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderDate, consumer, tenantOrderId, status, orderLineItems, deliveryPreferences, customAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderForCreation {\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    consumer: ").append(toIndentedString(consumer)).append("\n");
    sb.append("    tenantOrderId: ").append(toIndentedString(tenantOrderId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    orderLineItems: ").append(toIndentedString(orderLineItems)).append("\n");
    sb.append("    deliveryPreferences: ").append(toIndentedString(deliveryPreferences)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

