/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.DeliveryPreferences;
import com.example.connectorpoc.ft.model.OrderAllOf;
import com.example.connectorpoc.ft.model.OrderForCreation;
import com.example.connectorpoc.ft.model.OrderForCreationConsumer;
import com.example.connectorpoc.ft.model.OrderLineItem;
import com.example.connectorpoc.ft.model.OrderStatus;
import com.example.connectorpoc.ft.model.VersionedResource;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Order
 */
@JsonPropertyOrder({
  Order.JSON_PROPERTY_ORDER_DATE,
  Order.JSON_PROPERTY_CONSUMER,
  Order.JSON_PROPERTY_TENANT_ORDER_ID,
  Order.JSON_PROPERTY_STATUS,
  Order.JSON_PROPERTY_ORDER_LINE_ITEMS,
  Order.JSON_PROPERTY_DELIVERY_PREFERENCES,
  Order.JSON_PROPERTY_CUSTOM_ATTRIBUTES,
  Order.JSON_PROPERTY_VERSION,
  Order.JSON_PROPERTY_CREATED,
  Order.JSON_PROPERTY_LAST_MODIFIED,
  Order.JSON_PROPERTY_ID,
  Order.JSON_PROPERTY_ANONYMIZED
})
@JsonTypeName("Order")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class Order {
  public static final String JSON_PROPERTY_ORDER_DATE = "orderDate";
  private OffsetDateTime orderDate;

  public static final String JSON_PROPERTY_CONSUMER = "consumer";
  private OrderForCreationConsumer consumer;

  public static final String JSON_PROPERTY_TENANT_ORDER_ID = "tenantOrderId";
  private String tenantOrderId;

  public static final String JSON_PROPERTY_STATUS = "status";
  private OrderStatus status;

  public static final String JSON_PROPERTY_ORDER_LINE_ITEMS = "orderLineItems";
  private List<OrderLineItem> orderLineItems = new ArrayList<>();

  public static final String JSON_PROPERTY_DELIVERY_PREFERENCES = "deliveryPreferences";
  private DeliveryPreferences deliveryPreferences;

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTES = "customAttributes";
  private Object customAttributes;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ANONYMIZED = "anonymized";
  private Boolean anonymized;


  public Order orderDate(OffsetDateTime orderDate) {
    
    this.orderDate = orderDate;
    return this;
  }

   /**
   * The date this order was created at the supplying system.
   * @return orderDate
  **/
  @ApiModelProperty(example = "2020-02-03T08:45:50.525Z", required = true, value = "The date this order was created at the supplying system.")
  @JsonProperty(JSON_PROPERTY_ORDER_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getOrderDate() {
    return orderDate;
  }


  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }


  public Order consumer(OrderForCreationConsumer consumer) {
    
    this.consumer = consumer;
    return this;
  }

   /**
   * Get consumer
   * @return consumer
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONSUMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OrderForCreationConsumer getConsumer() {
    return consumer;
  }


  public void setConsumer(OrderForCreationConsumer consumer) {
    this.consumer = consumer;
  }


  public Order tenantOrderId(String tenantOrderId) {
    
    this.tenantOrderId = tenantOrderId;
    return this;
  }

   /**
   * Field can be used as a reference number in foreign systems, for example as a reference to the source system&#39;s identifier for this order.
   * @return tenantOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "R456728546", value = "Field can be used as a reference number in foreign systems, for example as a reference to the source system's identifier for this order.")
  @JsonProperty(JSON_PROPERTY_TENANT_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantOrderId() {
    return tenantOrderId;
  }


  public void setTenantOrderId(String tenantOrderId) {
    this.tenantOrderId = tenantOrderId;
  }


  public Order status(OrderStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OrderStatus getStatus() {
    return status;
  }


  public void setStatus(OrderStatus status) {
    this.status = status;
  }


  public Order orderLineItems(List<OrderLineItem> orderLineItems) {
    
    this.orderLineItems = orderLineItems;
    return this;
  }

  public Order addOrderLineItemsItem(OrderLineItem orderLineItemsItem) {
    this.orderLineItems.add(orderLineItemsItem);
    return this;
  }

   /**
   * Get orderLineItems
   * @return orderLineItems
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_LINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<OrderLineItem> getOrderLineItems() {
    return orderLineItems;
  }


  public void setOrderLineItems(List<OrderLineItem> orderLineItems) {
    this.orderLineItems = orderLineItems;
  }


  public Order deliveryPreferences(DeliveryPreferences deliveryPreferences) {
    
    this.deliveryPreferences = deliveryPreferences;
    return this;
  }

   /**
   * Get deliveryPreferences
   * @return deliveryPreferences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_PREFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryPreferences getDeliveryPreferences() {
    return deliveryPreferences;
  }


  public void setDeliveryPreferences(DeliveryPreferences deliveryPreferences) {
    this.deliveryPreferences = deliveryPreferences;
  }


  public Order customAttributes(Object customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

   /**
   * Attributes that can be added to the order. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attributes that can be added to the order. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(Object customAttributes) {
    this.customAttributes = customAttributes;
  }


  public Order version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public Order created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public Order lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public Order id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of this order. It is generated during creation automatically and suits as the primary identifier of the described entity.
   * @return id
  **/
  @ApiModelProperty(example = "LGMl2DuvPnfPoSHhYFOm", required = true, value = "The id of this order. It is generated during creation automatically and suits as the primary identifier of the described entity.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Order anonymized(Boolean anonymized) {
    
    this.anonymized = anonymized;
    return this;
  }

   /**
   * Indicates if gdpr related data was anonymized
   * @return anonymized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if gdpr related data was anonymized")
  @JsonProperty(JSON_PROPERTY_ANONYMIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnonymized() {
    return anonymized;
  }


  public void setAnonymized(Boolean anonymized) {
    this.anonymized = anonymized;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.orderDate, order.orderDate) &&
        Objects.equals(this.consumer, order.consumer) &&
        Objects.equals(this.tenantOrderId, order.tenantOrderId) &&
        Objects.equals(this.status, order.status) &&
        Objects.equals(this.orderLineItems, order.orderLineItems) &&
        Objects.equals(this.deliveryPreferences, order.deliveryPreferences) &&
        Objects.equals(this.customAttributes, order.customAttributes) &&
        Objects.equals(this.version, order.version) &&
        Objects.equals(this.created, order.created) &&
        Objects.equals(this.lastModified, order.lastModified) &&
        Objects.equals(this.id, order.id) &&
        Objects.equals(this.anonymized, order.anonymized);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderDate, consumer, tenantOrderId, status, orderLineItems, deliveryPreferences, customAttributes, version, created, lastModified, id, anonymized);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    consumer: ").append(toIndentedString(consumer)).append("\n");
    sb.append("    tenantOrderId: ").append(toIndentedString(tenantOrderId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    orderLineItems: ").append(toIndentedString(orderLineItems)).append("\n");
    sb.append("    deliveryPreferences: ").append(toIndentedString(deliveryPreferences)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    anonymized: ").append(toIndentedString(anonymized)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

