/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ParcelAllOfResult;
import com.example.connectorpoc.ft.model.ParcelStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ParcelAllOf
 */
@JsonPropertyOrder({
  ParcelAllOf.JSON_PROPERTY_ID,
  ParcelAllOf.JSON_PROPERTY_STATUS,
  ParcelAllOf.JSON_PROPERTY_ANONYMIZED,
  ParcelAllOf.JSON_PROPERTY_RESULT
})
@JsonTypeName("Parcel_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ParcelAllOf {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_STATUS = "status";
  private ParcelStatus status;

  public static final String JSON_PROPERTY_ANONYMIZED = "anonymized";
  private Boolean anonymized;

  public static final String JSON_PROPERTY_RESULT = "result";
  private ParcelAllOfResult result;


  public ParcelAllOf id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of this parcel. It is generated during creation automatically and suits as the primary identifier of the described entity.
   * @return id
  **/
  @ApiModelProperty(example = "95EWrieX09OmeriXIUbb", required = true, value = "The id of this parcel. It is generated during creation automatically and suits as the primary identifier of the described entity.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ParcelAllOf status(ParcelStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ParcelStatus getStatus() {
    return status;
  }


  public void setStatus(ParcelStatus status) {
    this.status = status;
  }


  public ParcelAllOf anonymized(Boolean anonymized) {
    
    this.anonymized = anonymized;
    return this;
  }

   /**
   * Indicates if gdpr related data was anonymized
   * @return anonymized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if gdpr related data was anonymized")
  @JsonProperty(JSON_PROPERTY_ANONYMIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnonymized() {
    return anonymized;
  }


  public void setAnonymized(Boolean anonymized) {
    this.anonymized = anonymized;
  }


  public ParcelAllOf result(ParcelAllOfResult result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ParcelAllOfResult getResult() {
    return result;
  }


  public void setResult(ParcelAllOfResult result) {
    this.result = result;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelAllOf parcelAllOf = (ParcelAllOf) o;
    return Objects.equals(this.id, parcelAllOf.id) &&
        Objects.equals(this.status, parcelAllOf.status) &&
        Objects.equals(this.anonymized, parcelAllOf.anonymized) &&
        Objects.equals(this.result, parcelAllOf.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, anonymized, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelAllOf {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    anonymized: ").append(toIndentedString(anonymized)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

