/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.TrackingStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Within this object you can find the result of the request after it has been processed (status &#x3D; DONE or FAILED)
 */
@ApiModel(description = "Within this object you can find the result of the request after it has been processed (status = DONE or FAILED)")
@JsonPropertyOrder({
  ParcelAllOfResult.JSON_PROPERTY_SUMMARY,
  ParcelAllOfResult.JSON_PROPERTY_LABEL_URL,
  ParcelAllOfResult.JSON_PROPERTY_PROXY_ID,
  ParcelAllOfResult.JSON_PROPERTY_CARRIER_TRACKING_NUMBER,
  ParcelAllOfResult.JSON_PROPERTY_TRACKING_URL,
  ParcelAllOfResult.JSON_PROPERTY_TRACKING_STATUS
})
@JsonTypeName("Parcel_allOf_result")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ParcelAllOfResult {
  public static final String JSON_PROPERTY_SUMMARY = "summary";
  private String summary;

  public static final String JSON_PROPERTY_LABEL_URL = "labelUrl";
  private String labelUrl;

  public static final String JSON_PROPERTY_PROXY_ID = "proxyId";
  private String proxyId;

  public static final String JSON_PROPERTY_CARRIER_TRACKING_NUMBER = "carrierTrackingNumber";
  private String carrierTrackingNumber;

  public static final String JSON_PROPERTY_TRACKING_URL = "trackingUrl";
  private String trackingUrl;

  public static final String JSON_PROPERTY_TRACKING_STATUS = "trackingStatus";
  private TrackingStatus trackingStatus;


  public ParcelAllOfResult summary(String summary) {
    
    this.summary = summary;
    return this;
  }

   /**
   * Summary of the result of the request in a human readable form.
   * @return summary
  **/
  @ApiModelProperty(example = "Package label was successfully requested at DHL.", required = true, value = "Summary of the result of the request in a human readable form.")
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSummary() {
    return summary;
  }


  public void setSummary(String summary) {
    this.summary = summary;
  }


  public ParcelAllOfResult labelUrl(String labelUrl) {
    
    this.labelUrl = labelUrl;
    return this;
  }

   /**
   * The URL where you can download the label relative to the path of this resource
   * @return labelUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "%%HOST%%/api/parcels/{parcelId}/labels/84168117830018.pdf", value = "The URL where you can download the label relative to the path of this resource")
  @JsonProperty(JSON_PROPERTY_LABEL_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLabelUrl() {
    return labelUrl;
  }


  public void setLabelUrl(String labelUrl) {
    this.labelUrl = labelUrl;
  }


  public ParcelAllOfResult proxyId(String proxyId) {
    
    this.proxyId = proxyId;
    return this;
  }

   /**
   * The ID of the corresponding job at the CEP proxy (if used)
   * @return proxyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3a186c51d4281acbecf5ed38805b1db92a9d668b", value = "The ID of the corresponding job at the CEP proxy (if used)")
  @JsonProperty(JSON_PROPERTY_PROXY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProxyId() {
    return proxyId;
  }


  public void setProxyId(String proxyId) {
    this.proxyId = proxyId;
  }


  public ParcelAllOfResult carrierTrackingNumber(String carrierTrackingNumber) {
    
    this.carrierTrackingNumber = carrierTrackingNumber;
    return this;
  }

   /**
   * Get carrierTrackingNumber
   * @return carrierTrackingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "84168117830018", value = "")
  @JsonProperty(JSON_PROPERTY_CARRIER_TRACKING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCarrierTrackingNumber() {
    return carrierTrackingNumber;
  }


  public void setCarrierTrackingNumber(String carrierTrackingNumber) {
    this.carrierTrackingNumber = carrierTrackingNumber;
  }


  public ParcelAllOfResult trackingUrl(String trackingUrl) {
    
    this.trackingUrl = trackingUrl;
    return this;
  }

   /**
   * The URL to track this parcel
   * @return trackingUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://track.shipcloud.io/3a186c51d4", value = "The URL to track this parcel")
  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackingUrl() {
    return trackingUrl;
  }


  public void setTrackingUrl(String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  public ParcelAllOfResult trackingStatus(TrackingStatus trackingStatus) {
    
    this.trackingStatus = trackingStatus;
    return this;
  }

   /**
   * Get trackingStatus
   * @return trackingStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRACKING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TrackingStatus getTrackingStatus() {
    return trackingStatus;
  }


  public void setTrackingStatus(TrackingStatus trackingStatus) {
    this.trackingStatus = trackingStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelAllOfResult parcelAllOfResult = (ParcelAllOfResult) o;
    return Objects.equals(this.summary, parcelAllOfResult.summary) &&
        Objects.equals(this.labelUrl, parcelAllOfResult.labelUrl) &&
        Objects.equals(this.proxyId, parcelAllOfResult.proxyId) &&
        Objects.equals(this.carrierTrackingNumber, parcelAllOfResult.carrierTrackingNumber) &&
        Objects.equals(this.trackingUrl, parcelAllOfResult.trackingUrl) &&
        Objects.equals(this.trackingStatus, parcelAllOfResult.trackingStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summary, labelUrl, proxyId, carrierTrackingNumber, trackingUrl, trackingStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelAllOfResult {\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    labelUrl: ").append(toIndentedString(labelUrl)).append("\n");
    sb.append("    proxyId: ").append(toIndentedString(proxyId)).append("\n");
    sb.append("    carrierTrackingNumber: ").append(toIndentedString(carrierTrackingNumber)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("    trackingStatus: ").append(toIndentedString(trackingStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

