/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ParcelForCreationDimensions
 */
@JsonPropertyOrder({
  ParcelForCreationDimensions.JSON_PROPERTY_WIDTH,
  ParcelForCreationDimensions.JSON_PROPERTY_HEIGHT,
  ParcelForCreationDimensions.JSON_PROPERTY_LENGTH,
  ParcelForCreationDimensions.JSON_PROPERTY_WEIGHT
})
@JsonTypeName("ParcelForCreation_dimensions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ParcelForCreationDimensions {
  public static final String JSON_PROPERTY_WIDTH = "width";
  private BigDecimal width;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private BigDecimal height;

  public static final String JSON_PROPERTY_LENGTH = "length";
  private BigDecimal length;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  private BigDecimal weight;


  public ParcelForCreationDimensions width(BigDecimal width) {
    
    this.width = width;
    return this;
  }

   /**
   * The width of the package (in cm)
   * @return width
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25.0", value = "The width of the package (in cm)")
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWidth() {
    return width;
  }


  public void setWidth(BigDecimal width) {
    this.width = width;
  }


  public ParcelForCreationDimensions height(BigDecimal height) {
    
    this.height = height;
    return this;
  }

   /**
   * The height of the package (in cm)
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "50.0", value = "The height of the package (in cm)")
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getHeight() {
    return height;
  }


  public void setHeight(BigDecimal height) {
    this.height = height;
  }


  public ParcelForCreationDimensions length(BigDecimal length) {
    
    this.length = length;
    return this;
  }

   /**
   * The length of the package (in cm)
   * @return length
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "100.0", value = "The length of the package (in cm)")
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLength() {
    return length;
  }


  public void setLength(BigDecimal length) {
    this.length = length;
  }


  public ParcelForCreationDimensions weight(BigDecimal weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * The weight of the package (in g)
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1700.0", value = "The weight of the package (in g)")
  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWeight() {
    return weight;
  }


  public void setWeight(BigDecimal weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelForCreationDimensions parcelForCreationDimensions = (ParcelForCreationDimensions) o;
    return Objects.equals(this.width, parcelForCreationDimensions.width) &&
        Objects.equals(this.height, parcelForCreationDimensions.height) &&
        Objects.equals(this.length, parcelForCreationDimensions.length) &&
        Objects.equals(this.weight, parcelForCreationDimensions.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(width, height, length, weight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelForCreationDimensions {\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

