/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ConsumerAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PickjobDeliveryInformationForCreationDetailsShipping
 */
@JsonPropertyOrder({
  PickjobDeliveryInformationForCreationDetailsShipping.JSON_PROPERTY_RECIPIENTADDRESS
})
@JsonTypeName("PickjobDeliveryInformationForCreation_details_shipping")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class PickjobDeliveryInformationForCreationDetailsShipping {
  public static final String JSON_PROPERTY_RECIPIENTADDRESS = "recipientaddress";
  private ConsumerAddress recipientaddress = null;


  public PickjobDeliveryInformationForCreationDetailsShipping recipientaddress(ConsumerAddress recipientaddress) {
    
    this.recipientaddress = recipientaddress;
    return this;
  }

   /**
   * Get recipientaddress
   * @return recipientaddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECIPIENTADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConsumerAddress getRecipientaddress() {
    return recipientaddress;
  }


  public void setRecipientaddress(ConsumerAddress recipientaddress) {
    this.recipientaddress = recipientaddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickjobDeliveryInformationForCreationDetailsShipping pickjobDeliveryInformationForCreationDetailsShipping = (PickjobDeliveryInformationForCreationDetailsShipping) o;
    return Objects.equals(this.recipientaddress, pickjobDeliveryInformationForCreationDetailsShipping.recipientaddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientaddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickjobDeliveryInformationForCreationDetailsShipping {\n");
    sb.append("    recipientaddress: ").append(toIndentedString(recipientaddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

