/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.PickJobStatus;
import com.example.connectorpoc.ft.model.PickLineItemForCreation;
import com.example.connectorpoc.ft.model.PickjobDeliveryInformationForCreation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PickJobForCreation
 */
@JsonPropertyOrder({
  PickJobForCreation.JSON_PROPERTY_ORDER_REF,
  PickJobForCreation.JSON_PROPERTY_ORDER_DATE,
  PickJobForCreation.JSON_PROPERTY_TENANT_ORDER_ID,
  PickJobForCreation.JSON_PROPERTY_FACILITY_REF,
  PickJobForCreation.JSON_PROPERTY_STATUS,
  PickJobForCreation.JSON_PROPERTY_PICK_LINE_ITEMS,
  PickJobForCreation.JSON_PROPERTY_DELIVERYINFORMATION,
  PickJobForCreation.JSON_PROPERTY_CUSTOM_ATTRIBUTES
})
@JsonTypeName("PickJobForCreation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class PickJobForCreation {
  public static final String JSON_PROPERTY_ORDER_REF = "orderRef";
  private String orderRef;

  public static final String JSON_PROPERTY_ORDER_DATE = "orderDate";
  private OffsetDateTime orderDate;

  public static final String JSON_PROPERTY_TENANT_ORDER_ID = "tenantOrderId";
  private String tenantOrderId;

  public static final String JSON_PROPERTY_FACILITY_REF = "facilityRef";
  private String facilityRef;

  public static final String JSON_PROPERTY_STATUS = "status";
  private PickJobStatus status;

  public static final String JSON_PROPERTY_PICK_LINE_ITEMS = "pickLineItems";
  private List<PickLineItemForCreation> pickLineItems = new ArrayList<>();

  public static final String JSON_PROPERTY_DELIVERYINFORMATION = "deliveryinformation";
  private PickjobDeliveryInformationForCreation deliveryinformation;

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTES = "customAttributes";
  private Object customAttributes;


  public PickJobForCreation orderRef(String orderRef) {
    
    this.orderRef = orderRef;
    return this;
  }

   /**
   * The id of the order reference. The given ID has to be present in the system.
   * @return orderRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "LGMl2DuvPnfPoSHhYFOm", value = "The id of the order reference. The given ID has to be present in the system.")
  @JsonProperty(JSON_PROPERTY_ORDER_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderRef() {
    return orderRef;
  }


  public void setOrderRef(String orderRef) {
    this.orderRef = orderRef;
  }


  public PickJobForCreation orderDate(OffsetDateTime orderDate) {
    
    this.orderDate = orderDate;
    return this;
  }

   /**
   * The date this order was created at the supplying system.
   * @return orderDate
  **/
  @ApiModelProperty(example = "2020-02-03T08:45:50.525Z", required = true, value = "The date this order was created at the supplying system.")
  @JsonProperty(JSON_PROPERTY_ORDER_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getOrderDate() {
    return orderDate;
  }


  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }


  public PickJobForCreation tenantOrderId(String tenantOrderId) {
    
    this.tenantOrderId = tenantOrderId;
    return this;
  }

   /**
   * Field can be used as a reference number in foreign systems, for example as a reference to the source system&#39;s identifier for this order.
   * @return tenantOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "R456728546", value = "Field can be used as a reference number in foreign systems, for example as a reference to the source system's identifier for this order.")
  @JsonProperty(JSON_PROPERTY_TENANT_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantOrderId() {
    return tenantOrderId;
  }


  public void setTenantOrderId(String tenantOrderId) {
    this.tenantOrderId = tenantOrderId;
  }


  public PickJobForCreation facilityRef(String facilityRef) {
    
    this.facilityRef = facilityRef;
    return this;
  }

   /**
   * The id of the facility reference. The given ID has to be present in the system.
   * @return facilityRef
  **/
  @ApiModelProperty(example = "Esb20gpHBL94X5NdMp3C", required = true, value = "The id of the facility reference. The given ID has to be present in the system.")
  @JsonProperty(JSON_PROPERTY_FACILITY_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFacilityRef() {
    return facilityRef;
  }


  public void setFacilityRef(String facilityRef) {
    this.facilityRef = facilityRef;
  }


  public PickJobForCreation status(PickJobStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PickJobStatus getStatus() {
    return status;
  }


  public void setStatus(PickJobStatus status) {
    this.status = status;
  }


  public PickJobForCreation pickLineItems(List<PickLineItemForCreation> pickLineItems) {
    
    this.pickLineItems = pickLineItems;
    return this;
  }

  public PickJobForCreation addPickLineItemsItem(PickLineItemForCreation pickLineItemsItem) {
    this.pickLineItems.add(pickLineItemsItem);
    return this;
  }

   /**
   * Get pickLineItems
   * @return pickLineItems
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PICK_LINE_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PickLineItemForCreation> getPickLineItems() {
    return pickLineItems;
  }


  public void setPickLineItems(List<PickLineItemForCreation> pickLineItems) {
    this.pickLineItems = pickLineItems;
  }


  public PickJobForCreation deliveryinformation(PickjobDeliveryInformationForCreation deliveryinformation) {
    
    this.deliveryinformation = deliveryinformation;
    return this;
  }

   /**
   * Get deliveryinformation
   * @return deliveryinformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERYINFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PickjobDeliveryInformationForCreation getDeliveryinformation() {
    return deliveryinformation;
  }


  public void setDeliveryinformation(PickjobDeliveryInformationForCreation deliveryinformation) {
    this.deliveryinformation = deliveryinformation;
  }


  public PickJobForCreation customAttributes(Object customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

   /**
   * Attributes that can be added to the pickjob. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attributes that can be added to the pickjob. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(Object customAttributes) {
    this.customAttributes = customAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickJobForCreation pickJobForCreation = (PickJobForCreation) o;
    return Objects.equals(this.orderRef, pickJobForCreation.orderRef) &&
        Objects.equals(this.orderDate, pickJobForCreation.orderDate) &&
        Objects.equals(this.tenantOrderId, pickJobForCreation.tenantOrderId) &&
        Objects.equals(this.facilityRef, pickJobForCreation.facilityRef) &&
        Objects.equals(this.status, pickJobForCreation.status) &&
        Objects.equals(this.pickLineItems, pickJobForCreation.pickLineItems) &&
        Objects.equals(this.deliveryinformation, pickJobForCreation.deliveryinformation) &&
        Objects.equals(this.customAttributes, pickJobForCreation.customAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderRef, orderDate, tenantOrderId, facilityRef, status, pickLineItems, deliveryinformation, customAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickJobForCreation {\n");
    sb.append("    orderRef: ").append(toIndentedString(orderRef)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    tenantOrderId: ").append(toIndentedString(tenantOrderId)).append("\n");
    sb.append("    facilityRef: ").append(toIndentedString(facilityRef)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    pickLineItems: ").append(toIndentedString(pickLineItems)).append("\n");
    sb.append("    deliveryinformation: ").append(toIndentedString(deliveryinformation)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

