/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PickjobDeliveryInformationForCreationDetailsCollect
 */
@JsonPropertyOrder({
  PickjobDeliveryInformationForCreationDetailsCollect.JSON_PROPERTY_IDENTIFIER
})
@JsonTypeName("PickjobDeliveryInformationForCreation_details_collect")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class PickjobDeliveryInformationForCreationDetailsCollect {
  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  private String identifier;


  public PickjobDeliveryInformationForCreationDetailsCollect identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Includes information about Click &amp; Collect recipient
   * @return identifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Includes information about Click & Collect recipient")
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickjobDeliveryInformationForCreationDetailsCollect pickjobDeliveryInformationForCreationDetailsCollect = (PickjobDeliveryInformationForCreationDetailsCollect) o;
    return Objects.equals(this.identifier, pickjobDeliveryInformationForCreationDetailsCollect.identifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickjobDeliveryInformationForCreationDetailsCollect {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

