/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.DeliveryInformation;
import com.example.connectorpoc.ft.model.ShipmentAllOf;
import com.example.connectorpoc.ft.model.ShipmentForCreation;
import com.example.connectorpoc.ft.model.ShipmentStatus;
import com.example.connectorpoc.ft.model.StrippedParcel;
import com.example.connectorpoc.ft.model.VersionedResource;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Shipment
 */
@JsonPropertyOrder({
  Shipment.JSON_PROPERTY_PICK_JOB_REF,
  Shipment.JSON_PROPERTY_DELIVERY_INFORMATION,
  Shipment.JSON_PROPERTY_VERSION,
  Shipment.JSON_PROPERTY_CREATED,
  Shipment.JSON_PROPERTY_LAST_MODIFIED,
  Shipment.JSON_PROPERTY_ID,
  Shipment.JSON_PROPERTY_FACILITY_REF,
  Shipment.JSON_PROPERTY_STATUS,
  Shipment.JSON_PROPERTY_PARCELS,
  Shipment.JSON_PROPERTY_TARGET_TIME,
  Shipment.JSON_PROPERTY_ANONYMIZED
})
@JsonTypeName("Shipment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class Shipment {
  public static final String JSON_PROPERTY_PICK_JOB_REF = "pickJobRef";
  private String pickJobRef;

  public static final String JSON_PROPERTY_DELIVERY_INFORMATION = "deliveryInformation";
  private DeliveryInformation deliveryInformation;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_FACILITY_REF = "facilityRef";
  private String facilityRef;

  public static final String JSON_PROPERTY_STATUS = "status";
  private ShipmentStatus status;

  public static final String JSON_PROPERTY_PARCELS = "parcels";
  private List<StrippedParcel> parcels = null;

  public static final String JSON_PROPERTY_TARGET_TIME = "targetTime";
  private OffsetDateTime targetTime;

  public static final String JSON_PROPERTY_ANONYMIZED = "anonymized";
  private Boolean anonymized = false;


  public Shipment pickJobRef(String pickJobRef) {
    
    this.pickJobRef = pickJobRef;
    return this;
  }

   /**
   * The reference to the pickjob for which the shipment is assigned to
   * @return pickJobRef
  **/
  @ApiModelProperty(example = "ca525716-7208-4a63-a2a6-11274eb37f67-0", required = true, value = "The reference to the pickjob for which the shipment is assigned to")
  @JsonProperty(JSON_PROPERTY_PICK_JOB_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPickJobRef() {
    return pickJobRef;
  }


  public void setPickJobRef(String pickJobRef) {
    this.pickJobRef = pickJobRef;
  }


  public Shipment deliveryInformation(DeliveryInformation deliveryInformation) {
    
    this.deliveryInformation = deliveryInformation;
    return this;
  }

   /**
   * Get deliveryInformation
   * @return deliveryInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryInformation getDeliveryInformation() {
    return deliveryInformation;
  }


  public void setDeliveryInformation(DeliveryInformation deliveryInformation) {
    this.deliveryInformation = deliveryInformation;
  }


  public Shipment version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public Shipment created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public Shipment lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public Shipment id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of this Shipment. It is generated during creation automatically and suits as the primary identifier of the described entity.
   * @return id
  **/
  @ApiModelProperty(example = "95EWrieX09OmeriXIUbb", required = true, value = "The id of this Shipment. It is generated during creation automatically and suits as the primary identifier of the described entity.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Shipment facilityRef(String facilityRef) {
    
    this.facilityRef = facilityRef;
    return this;
  }

   /**
   * The id of the facility reference.
   * @return facilityRef
  **/
  @ApiModelProperty(example = "Esb20gpHBL94X5NdMp3C", required = true, value = "The id of the facility reference.")
  @JsonProperty(JSON_PROPERTY_FACILITY_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFacilityRef() {
    return facilityRef;
  }


  public void setFacilityRef(String facilityRef) {
    this.facilityRef = facilityRef;
  }


  public Shipment status(ShipmentStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShipmentStatus getStatus() {
    return status;
  }


  public void setStatus(ShipmentStatus status) {
    this.status = status;
  }


  public Shipment parcels(List<StrippedParcel> parcels) {
    
    this.parcels = parcels;
    return this;
  }

  public Shipment addParcelsItem(StrippedParcel parcelsItem) {
    if (this.parcels == null) {
      this.parcels = new ArrayList<>();
    }
    this.parcels.add(parcelsItem);
    return this;
  }

   /**
   * Get parcels
   * @return parcels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARCELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<StrippedParcel> getParcels() {
    return parcels;
  }


  public void setParcels(List<StrippedParcel> parcels) {
    this.parcels = parcels;
  }


  public Shipment targetTime(OffsetDateTime targetTime) {
    
    this.targetTime = targetTime;
    return this;
  }

   /**
   * At which time the result is expected.
   * @return targetTime
  **/
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", required = true, value = "At which time the result is expected.")
  @JsonProperty(JSON_PROPERTY_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTargetTime() {
    return targetTime;
  }


  public void setTargetTime(OffsetDateTime targetTime) {
    this.targetTime = targetTime;
  }


  public Shipment anonymized(Boolean anonymized) {
    
    this.anonymized = anonymized;
    return this;
  }

   /**
   * Indicates if gdpr related data was anonymized
   * @return anonymized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if gdpr related data was anonymized")
  @JsonProperty(JSON_PROPERTY_ANONYMIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnonymized() {
    return anonymized;
  }


  public void setAnonymized(Boolean anonymized) {
    this.anonymized = anonymized;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shipment shipment = (Shipment) o;
    return Objects.equals(this.pickJobRef, shipment.pickJobRef) &&
        Objects.equals(this.deliveryInformation, shipment.deliveryInformation) &&
        Objects.equals(this.version, shipment.version) &&
        Objects.equals(this.created, shipment.created) &&
        Objects.equals(this.lastModified, shipment.lastModified) &&
        Objects.equals(this.id, shipment.id) &&
        Objects.equals(this.facilityRef, shipment.facilityRef) &&
        Objects.equals(this.status, shipment.status) &&
        Objects.equals(this.parcels, shipment.parcels) &&
        Objects.equals(this.targetTime, shipment.targetTime) &&
        Objects.equals(this.anonymized, shipment.anonymized);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pickJobRef, deliveryInformation, version, created, lastModified, id, facilityRef, status, parcels, targetTime, anonymized);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shipment {\n");
    sb.append("    pickJobRef: ").append(toIndentedString(pickJobRef)).append("\n");
    sb.append("    deliveryInformation: ").append(toIndentedString(deliveryInformation)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    facilityRef: ").append(toIndentedString(facilityRef)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    parcels: ").append(toIndentedString(parcels)).append("\n");
    sb.append("    targetTime: ").append(toIndentedString(targetTime)).append("\n");
    sb.append("    anonymized: ").append(toIndentedString(anonymized)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

