/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.ShipmentStatus;
import com.example.connectorpoc.ft.model.StrippedParcel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ShipmentAllOf
 */
@JsonPropertyOrder({
  ShipmentAllOf.JSON_PROPERTY_ID,
  ShipmentAllOf.JSON_PROPERTY_FACILITY_REF,
  ShipmentAllOf.JSON_PROPERTY_STATUS,
  ShipmentAllOf.JSON_PROPERTY_PARCELS,
  ShipmentAllOf.JSON_PROPERTY_TARGET_TIME,
  ShipmentAllOf.JSON_PROPERTY_ANONYMIZED
})
@JsonTypeName("Shipment_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class ShipmentAllOf {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_FACILITY_REF = "facilityRef";
  private String facilityRef;

  public static final String JSON_PROPERTY_STATUS = "status";
  private ShipmentStatus status;

  public static final String JSON_PROPERTY_PARCELS = "parcels";
  private List<StrippedParcel> parcels = null;

  public static final String JSON_PROPERTY_TARGET_TIME = "targetTime";
  private OffsetDateTime targetTime;

  public static final String JSON_PROPERTY_ANONYMIZED = "anonymized";
  private Boolean anonymized = false;


  public ShipmentAllOf id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of this Shipment. It is generated during creation automatically and suits as the primary identifier of the described entity.
   * @return id
  **/
  @ApiModelProperty(example = "95EWrieX09OmeriXIUbb", required = true, value = "The id of this Shipment. It is generated during creation automatically and suits as the primary identifier of the described entity.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ShipmentAllOf facilityRef(String facilityRef) {
    
    this.facilityRef = facilityRef;
    return this;
  }

   /**
   * The id of the facility reference.
   * @return facilityRef
  **/
  @ApiModelProperty(example = "Esb20gpHBL94X5NdMp3C", required = true, value = "The id of the facility reference.")
  @JsonProperty(JSON_PROPERTY_FACILITY_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFacilityRef() {
    return facilityRef;
  }


  public void setFacilityRef(String facilityRef) {
    this.facilityRef = facilityRef;
  }


  public ShipmentAllOf status(ShipmentStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ShipmentStatus getStatus() {
    return status;
  }


  public void setStatus(ShipmentStatus status) {
    this.status = status;
  }


  public ShipmentAllOf parcels(List<StrippedParcel> parcels) {
    
    this.parcels = parcels;
    return this;
  }

  public ShipmentAllOf addParcelsItem(StrippedParcel parcelsItem) {
    if (this.parcels == null) {
      this.parcels = new ArrayList<>();
    }
    this.parcels.add(parcelsItem);
    return this;
  }

   /**
   * Get parcels
   * @return parcels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARCELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<StrippedParcel> getParcels() {
    return parcels;
  }


  public void setParcels(List<StrippedParcel> parcels) {
    this.parcels = parcels;
  }


  public ShipmentAllOf targetTime(OffsetDateTime targetTime) {
    
    this.targetTime = targetTime;
    return this;
  }

   /**
   * At which time the result is expected.
   * @return targetTime
  **/
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", required = true, value = "At which time the result is expected.")
  @JsonProperty(JSON_PROPERTY_TARGET_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTargetTime() {
    return targetTime;
  }


  public void setTargetTime(OffsetDateTime targetTime) {
    this.targetTime = targetTime;
  }


  public ShipmentAllOf anonymized(Boolean anonymized) {
    
    this.anonymized = anonymized;
    return this;
  }

   /**
   * Indicates if gdpr related data was anonymized
   * @return anonymized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if gdpr related data was anonymized")
  @JsonProperty(JSON_PROPERTY_ANONYMIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnonymized() {
    return anonymized;
  }


  public void setAnonymized(Boolean anonymized) {
    this.anonymized = anonymized;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentAllOf shipmentAllOf = (ShipmentAllOf) o;
    return Objects.equals(this.id, shipmentAllOf.id) &&
        Objects.equals(this.facilityRef, shipmentAllOf.facilityRef) &&
        Objects.equals(this.status, shipmentAllOf.status) &&
        Objects.equals(this.parcels, shipmentAllOf.parcels) &&
        Objects.equals(this.targetTime, shipmentAllOf.targetTime) &&
        Objects.equals(this.anonymized, shipmentAllOf.anonymized);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, facilityRef, status, parcels, targetTime, anonymized);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentAllOf {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    facilityRef: ").append(toIndentedString(facilityRef)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    parcels: ").append(toIndentedString(parcels)).append("\n");
    sb.append("    targetTime: ").append(toIndentedString(targetTime)).append("\n");
    sb.append("    anonymized: ").append(toIndentedString(anonymized)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

