/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.Address;
import com.example.connectorpoc.ft.model.AddressPhoneNumbers;
import com.example.connectorpoc.ft.model.FacilityStatus;
import com.example.connectorpoc.ft.model.StrippedFacilityAllOf;
import com.example.connectorpoc.ft.model.VersionedResource;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * StrippedFacility
 */
@JsonPropertyOrder({
  StrippedFacility.JSON_PROPERTY_VERSION,
  StrippedFacility.JSON_PROPERTY_CREATED,
  StrippedFacility.JSON_PROPERTY_LAST_MODIFIED,
  StrippedFacility.JSON_PROPERTY_STREET,
  StrippedFacility.JSON_PROPERTY_HOUSE_NUMBER,
  StrippedFacility.JSON_PROPERTY_POSTAL_CODE,
  StrippedFacility.JSON_PROPERTY_CITY,
  StrippedFacility.JSON_PROPERTY_COUNTRY,
  StrippedFacility.JSON_PROPERTY_PHONE_NUMBERS,
  StrippedFacility.JSON_PROPERTY_ADDITIONAL_ADDRESS_INFO,
  StrippedFacility.JSON_PROPERTY_CUSTOM_ATTRIBUTES,
  StrippedFacility.JSON_PROPERTY_ID,
  StrippedFacility.JSON_PROPERTY_NAME,
  StrippedFacility.JSON_PROPERTY_TENANT_FACILITY_ID,
  StrippedFacility.JSON_PROPERTY_STATUS
})
@JsonTypeName("StrippedFacility")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class StrippedFacility {
  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_STREET = "street";
  private String street;

  public static final String JSON_PROPERTY_HOUSE_NUMBER = "houseNumber";
  private String houseNumber;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_PHONE_NUMBERS = "phoneNumbers";
  private List<AddressPhoneNumbers> phoneNumbers = null;

  public static final String JSON_PROPERTY_ADDITIONAL_ADDRESS_INFO = "additionalAddressInfo";
  private String additionalAddressInfo;

  public static final String JSON_PROPERTY_CUSTOM_ATTRIBUTES = "customAttributes";
  private Object customAttributes;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TENANT_FACILITY_ID = "tenantFacilityId";
  private String tenantFacilityId;

  public static final String JSON_PROPERTY_STATUS = "status";
  private FacilityStatus status;


  public StrippedFacility version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public StrippedFacility created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public StrippedFacility lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public StrippedFacility street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
  @ApiModelProperty(example = "Hauptstr.", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStreet() {
    return street;
  }


  public void setStreet(String street) {
    this.street = street;
  }


  public StrippedFacility houseNumber(String houseNumber) {
    
    this.houseNumber = houseNumber;
    return this;
  }

   /**
   * Get houseNumber
   * @return houseNumber
  **/
  @ApiModelProperty(example = "42a", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_HOUSE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHouseNumber() {
    return houseNumber;
  }


  public void setHouseNumber(String houseNumber) {
    this.houseNumber = houseNumber;
  }


  public StrippedFacility postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @ApiModelProperty(example = "40764", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public StrippedFacility city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "Langenfeld", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public StrippedFacility country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * A two-digit country code as per ISO 3166-1 alpha-2
   * @return country
  **/
  @ApiModelProperty(example = "DE", required = true, value = "A two-digit country code as per ISO 3166-1 alpha-2")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public StrippedFacility phoneNumbers(List<AddressPhoneNumbers> phoneNumbers) {
    
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public StrippedFacility addPhoneNumbersItem(AddressPhoneNumbers phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * Get phoneNumbers
   * @return phoneNumbers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHONE_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AddressPhoneNumbers> getPhoneNumbers() {
    return phoneNumbers;
  }


  public void setPhoneNumbers(List<AddressPhoneNumbers> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }


  public StrippedFacility additionalAddressInfo(String additionalAddressInfo) {
    
    this.additionalAddressInfo = additionalAddressInfo;
    return this;
  }

   /**
   * Get additionalAddressInfo
   * @return additionalAddressInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "to care of: Mrs. Müller", value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADDRESS_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalAddressInfo() {
    return additionalAddressInfo;
  }


  public void setAdditionalAddressInfo(String additionalAddressInfo) {
    this.additionalAddressInfo = additionalAddressInfo;
  }


  public StrippedFacility customAttributes(Object customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

   /**
   * Attributes that can be added to the address. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attributes that can be added to the address. These attributes cannot be used within fulfillment processes, but it could be useful to have the informations carried here.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(Object customAttributes) {
    this.customAttributes = customAttributes;
  }


  public StrippedFacility id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public StrippedFacility name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name of the facility
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Köln store", value = "name of the facility")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public StrippedFacility tenantFacilityId(String tenantFacilityId) {
    
    this.tenantFacilityId = tenantFacilityId;
    return this;
  }

   /**
   * The id of the facility in the tenants own system
   * @return tenantFacilityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "K12345", value = "The id of the facility in the tenants own system")
  @JsonProperty(JSON_PROPERTY_TENANT_FACILITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantFacilityId() {
    return tenantFacilityId;
  }


  public void setTenantFacilityId(String tenantFacilityId) {
    this.tenantFacilityId = tenantFacilityId;
  }


  public StrippedFacility status(FacilityStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FacilityStatus getStatus() {
    return status;
  }


  public void setStatus(FacilityStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StrippedFacility strippedFacility = (StrippedFacility) o;
    return Objects.equals(this.version, strippedFacility.version) &&
        Objects.equals(this.created, strippedFacility.created) &&
        Objects.equals(this.lastModified, strippedFacility.lastModified) &&
        Objects.equals(this.street, strippedFacility.street) &&
        Objects.equals(this.houseNumber, strippedFacility.houseNumber) &&
        Objects.equals(this.postalCode, strippedFacility.postalCode) &&
        Objects.equals(this.city, strippedFacility.city) &&
        Objects.equals(this.country, strippedFacility.country) &&
        Objects.equals(this.phoneNumbers, strippedFacility.phoneNumbers) &&
        Objects.equals(this.additionalAddressInfo, strippedFacility.additionalAddressInfo) &&
        Objects.equals(this.customAttributes, strippedFacility.customAttributes) &&
        Objects.equals(this.id, strippedFacility.id) &&
        Objects.equals(this.name, strippedFacility.name) &&
        Objects.equals(this.tenantFacilityId, strippedFacility.tenantFacilityId) &&
        Objects.equals(this.status, strippedFacility.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, created, lastModified, street, houseNumber, postalCode, city, country, phoneNumbers, additionalAddressInfo, customAttributes, id, name, tenantFacilityId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StrippedFacility {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    additionalAddressInfo: ").append(toIndentedString(additionalAddressInfo)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tenantFacilityId: ").append(toIndentedString(tenantFacilityId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

