/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.connectorpoc.ft.model.PickJobStatus;
import com.example.connectorpoc.ft.model.StrippedPickJobAllOf;
import com.example.connectorpoc.ft.model.VersionedResource;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * StrippedPickJob
 */
@JsonPropertyOrder({
  StrippedPickJob.JSON_PROPERTY_VERSION,
  StrippedPickJob.JSON_PROPERTY_CREATED,
  StrippedPickJob.JSON_PROPERTY_LAST_MODIFIED,
  StrippedPickJob.JSON_PROPERTY_ID,
  StrippedPickJob.JSON_PROPERTY_STATUS,
  StrippedPickJob.JSON_PROPERTY_ORDER_REF,
  StrippedPickJob.JSON_PROPERTY_FACILITY_REF
})
@JsonTypeName("StrippedPickJob")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T17:37:48.618828+01:00[Europe/Berlin]")
public class StrippedPickJob {
  public static final String JSON_PROPERTY_VERSION = "version";
  private Long version;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private OffsetDateTime lastModified;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_STATUS = "status";
  private PickJobStatus status;

  public static final String JSON_PROPERTY_ORDER_REF = "orderRef";
  private String orderRef;

  public static final String JSON_PROPERTY_FACILITY_REF = "facilityRef";
  private String facilityRef;


  public StrippedPickJob version(Long version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the document to be used in optimistic locking mechanisms.
   * @return version
  **/
  @ApiModelProperty(example = "42", required = true, value = "The version of the document to be used in optimistic locking mechanisms.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVersion() {
    return version;
  }


  public void setVersion(Long version) {
    this.version = version;
  }


  public StrippedPickJob created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The date this order was created at the platform. This value is generated by the service.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T08:45:51.525Z", value = "The date this order was created at the platform. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public StrippedPickJob lastModified(OffsetDateTime lastModified) {
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * The date this order was modified last. This value is generated by the service.
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-02-03T09:45:51.525Z", value = "The date this order was modified last. This value is generated by the service.")
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastModified() {
    return lastModified;
  }


  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }


  public StrippedPickJob id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public StrippedPickJob status(PickJobStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PickJobStatus getStatus() {
    return status;
  }


  public void setStatus(PickJobStatus status) {
    this.status = status;
  }


  public StrippedPickJob orderRef(String orderRef) {
    
    this.orderRef = orderRef;
    return this;
  }

   /**
   * The id of the order that lead to the creation of this pickjob. Can be empty / not present when the pickjob was created without having an order.
   * @return orderRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "LGMl2DuvPnfPoSHhYFOm", value = "The id of the order that lead to the creation of this pickjob. Can be empty / not present when the pickjob was created without having an order.")
  @JsonProperty(JSON_PROPERTY_ORDER_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderRef() {
    return orderRef;
  }


  public void setOrderRef(String orderRef) {
    this.orderRef = orderRef;
  }


  public StrippedPickJob facilityRef(String facilityRef) {
    
    this.facilityRef = facilityRef;
    return this;
  }

   /**
   * The id of the facility reference. The given ID has to be present in the system.
   * @return facilityRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Esb20gpHBL94X5NdMp3C", value = "The id of the facility reference. The given ID has to be present in the system.")
  @JsonProperty(JSON_PROPERTY_FACILITY_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFacilityRef() {
    return facilityRef;
  }


  public void setFacilityRef(String facilityRef) {
    this.facilityRef = facilityRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StrippedPickJob strippedPickJob = (StrippedPickJob) o;
    return Objects.equals(this.version, strippedPickJob.version) &&
        Objects.equals(this.created, strippedPickJob.created) &&
        Objects.equals(this.lastModified, strippedPickJob.lastModified) &&
        Objects.equals(this.id, strippedPickJob.id) &&
        Objects.equals(this.status, strippedPickJob.status) &&
        Objects.equals(this.orderRef, strippedPickJob.orderRef) &&
        Objects.equals(this.facilityRef, strippedPickJob.facilityRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, created, lastModified, id, status, orderRef, facilityRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StrippedPickJob {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    orderRef: ").append(toIndentedString(orderRef)).append("\n");
    sb.append("    facilityRef: ").append(toIndentedString(facilityRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

