/*
 * fulfillmenttools API for tenant %%PROJECT_ID%%
 * This is the fulfillmenttools API for tenant %%PROJECT_ID%%
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: api@fulfillmenttools.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.connectorpoc.ft.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The state of the KEP
 */
public enum TrackingStatus {
  
  REGISTERED("registered"),
  
  PICKED_UP("picked_up"),
  
  DELIVERED("delivered"),
  
  NOT_DELIVERED("not_delivered"),
  
  TRANSIT("transit"),
  
  EXCEPTION("exception"),
  
  OUT_FOR_DELIVERY("out_for_delivery"),
  
  DESTROYED("destroyed"),
  
  UNKNOWN("unknown"),
  
  CANCELED("canceled"),
  
  AWAITS_PICKUP_BY_RECEIVER("awaits_pickup_by_receiver"),
  
  DELAYED("delayed"),
  
  NOTIFICATION("notification");

  private String value;

  TrackingStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TrackingStatus fromValue(String value) {
    for (TrackingStatus b : TrackingStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

